spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL:jdbc:mysql://localhost:3306/SocketDemo}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:kang0525@}

    hikari:
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secretKey: ${SECRET_KEY:askjfnaskfno12840148}
  accessExp: 1470
  refreshExp: 7400
